### ISSUE TITLE
Truncation of stdout

### ISSUE THREAD

**Issue by bede** [kennethreitz/envoy#73]
I have a command that sends 600kB of output to stdout.
```
cat /path/to/file.fastq | seqtk sample - 3656 | seqtk seq -a -
```

Called with `os.system()`, it does exactly that, however, when run through Envoy the output is truncated to 6kB. I've tried using the inbuilt `.std_out`, redirection, and `tee`ing to an output file, but the output is always truncated. Is this a problem related to pipes? I have many calls to `envoy.run()` in the same script – does a buffer need flushing? I'm unfamiliar with the finer points of subprocess – is this a problem inherited from subprocess, or is it envoy, or something else entirely?

**Comment by timgkeller** [comment]
I can confirm the issue. An example:

# cat /var/log/nginx/access.log | wc -l
3368
# python -c "from envoy import run; print run('cat /var/log/nginx/access.log | wc -l').std_out"
47

**Comment by bede** [comment]
Thanks @timgkeller – I should probably have presented a simpler test case. Maybe @kennethreitz could shine some light on this?

**Comment by chassing** [comment]
@bede I've also reported (+PR) this issue years ago, see #45, just read the "resolution" for it. I think this project is abandoned :worried: and so I've switched to sh (https://pypi.python.org/pypi/sh)

**Comment by bede** [comment]
Ah, that's a pity. Cheers for the recommendation @chassing

**Comment by bede** [comment]
I'm sorry to bother you again @chassing, but are you aware of any more Envoy-like solutions than Sh? Sh seems very powerful, but the syntax (at least as I understand it) becomes quite cumbersome for longer shell commands and with multiple pipes.

**Comment by chassing** [comment]
@bede You are right, the sh usage is a little bit different. Unfortunately I do not know any other envoy-like solutions, but if you found one, drop me a line.

**Comment by kernc** [comment]
@bede https://plumbum.readthedocs.org/ https://docs.python.org/3/library/pipes.html

**Comment by eugene-eeo** [comment]
@bede the problem is that envoy does not have "proper" piping support, see [core.py](https://github.com/kennethreitz/envoy/blob/master/envoy/core.py#L210) where only around 10kB of data is passed to the next command. With that being said, you should try [proclib](https://github.com/datalib/proclib) for proper piping support.

**Comment by bede** [comment]
Thanks @chassing @kernc @eugene-eeo : )
I hadn't come across plumbum or proclib, both of which look interesting. The streaming in Proclib is just what I'm after.

I think it's probably time this one was closed. Thanks again for the help.
